spring.application.name=secure-order-api

spring.datasource.url=jdbc:mysql://localhost:3306/secure_order_api
spring.datasource.username=root
spring.datasource.password=${DB-PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true

